import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/home.module.css'
import { AuthSession } from '@supabase/supabase-js'
import Auth from '../components/auth'
import { supabase } from '../lib/supabaseClient'

export default function Home() {
  const [session, setSession] = useState<AuthSession | null>(null)

  useEffect(() => {
    setSession(supabase.auth.session())

    supabase.auth.onAuthStateChange((_event: string, session: AuthSession | null) => {
      setSession(session)
    })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Trunk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <div>Trunk</div>
        </h1>
        {/* <code className={styles.code}>alpha</code> */}
        <p className={styles.description}>
          Literature review for high-performing teams
        </p>
        {!session ? (
          <Auth/>
        ): (
          <>
            {session.user &&
              <p className={styles.userEmail}>{session.user.email}</p>
            }
            <Link href="/workspace">
              <button className='btn btn--secondary'>ENTER TO WORKSPACE</button>
            </Link>
          </>
        )}
      </main>
      <div className={styles.secret}>
        <Link href="/workspace">
        <a>secret passage</a>
        </Link>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://jellypbc.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Produced by Jelly Public Benefit Corporation
        </a>
      </footer>
    </div>
  )
}
